[package]
name = "routing-derive"
version = "0.1.1"
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]

[dependencies]
error-chain = "0.11"
regex = "0.2"
syn = "0.11"
quote = "0.3"

[lib]
proc-macro = true
